name: Update Repository Tree

on:
  push:
    branches:
      - main

jobs:
  update-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Generate tree structure
        run: tree -L 2 > tree.txt

      - name: Update README.md
        run: |
          # Crear un archivo temporal para el README.md actualizado
          awk '
          # Eliminar solo el contenido entre las etiquetas, pero mantener las etiquetas y las líneas vacías
          /<!-- START TREE STRUCTURE -->/{flag=1; print; next}
          /<!-- END TREE STRUCTURE -->/{flag=0; print}
          !flag' README.md > temp.md

          # Insertar las etiquetas y el nuevo contenido después de la sección "## Estructura del repositorio"
          awk '
          # Imprimir la línea "## Estructura del repositorio" y las etiquetas
          /## Estructura del repositorio/{print; print "<!-- START TREE STRUCTURE -->"; next}
          /<!-- START TREE STRUCTURE -->/{flag=1; next}
          /<!-- END TREE STRUCTURE -->/{flag=0; next}
          !flag' temp.md > updated.md

          # Agregar el contenido del árbol y las etiquetas de cierre
          echo "<!-- END TREE STRUCTURE -->" >> updated.md
          cat tree.txt >> updated.md

          # Reemplazar README.md con el archivo actualizado
          mv updated.md README.md

          # Configurar git, hacer commit y push
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Actualiza la estructura del repositorio"
          git pull origin main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
