name: Update Repository Tree

on:
  push:
    branches:
      - main

jobs:
  update-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Generate tree structure
        run: tree -L 2 > structure.txt

      - name: Update README.md
        run: |

         sed -i '/##Estructura del repositorio/,/##/{//!d}' README.md
         sed -i '/##Estructura del repositorio/r structure.txt' README.md

          # Configurar git, hacer commit y push
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Actualiza la estructura del repositorio"
          git pull origin main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
