name: Update Repository Tree

on:
  push:
    branches:
      - main  # O la rama que estés utilizando

jobs:
  update-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tree
        run: sudo apt-get install tree

      - name: Generate tree structure
        run: tree -L 2 > tree.txt  # Ajusta el nivel de profundidad si es necesario

      - name: Update README.md
        run: |
          # Reemplazar el contenido entre los marcadores
          sed -i '/<!-- START TREE STRUCTURE -->/,+1d' README.md
          sed -i '/<!-- END TREE STRUCTURE -->/d' README.md
          echo "<!-- START TREE STRUCTURE -->" >> README.md
          cat tree.txt >> README.md
          echo "<!-- END TREE STRUCTURE -->" >> README.md
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Actualiza la estructura del repositorio"
          git push
