name: Update Repository Tree

on:
  push:
    branches:
      - main

jobs:
  update-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Install tree
        run: sudo apt-get install tree

      - name: Generate tree structure
        run: tree -L 2 > tree.txt

      - name: Update README.md
        run: |
          sed -i '/<!-- START TREE STRUCTURE -->/,+1d' README.md
          sed -i '/<!-- END TREE STRUCTURE -->/d' README.md
          echo "<!-- START TREE STRUCTURE -->" >> README.md
          cat tree.txt >> README.md
          echo "<!-- END TREE STRUCTURE -->" >> README.md
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Actualiza la estructura del repositorio"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
